n = input('\033[4;37mdigite qualquer coisa\033[m ')
print('Seu tipo primitivo é',type(n),'\033[m')
print('Tem número ou letra? {}{}{}'.format('\033[0;31m',n.isalnum(),'\033[m'))
print('Tem apenas letras?','\033[32m',n.isalpha(),'\033[m')
print('Possue apenas números?','\033[31m',n.isdigit(),'\033[m')
print('Há apenas decimais entre 0 - 9 no valor?','\033[32m',n.isdecimal(),'\033[m')
print('É numérico o seu valor?',n.isnumeric())
print('O valor pode ser impresso?',n.isprintable())
print('Tem espaço?',n.isspace())
print('Está em letras minuculas?',n.islower())
print('Tem apenas valores no maísculo?',n.isupper())
print('Ela está capitalazada?',n.istitle())
